### PR TITLE
Add DNS Support

### PR DESCRIPTION
**Pull request by linuxlikerqq**
Add DNS Support at dns directory

### CODE REVIEW

**Comment by linuxlikerqq** [comment]
I'm writing a ddns server based on Aliyun DNS Service.I hope you could give me some advice in oder to getting my dns sdk code be merged. Thank you.

**Comment by denverdino** [comment]
Thanks !!! That is very nice. 

If you can remove the spm from the doc link, that will be cooler. E.g. 
from 
 https://docs.aliyun.com/?spm=5176.100054.201.106.OeZ3dN#/pub/dns/api-reference/record-related&UpdateDomainRecord
to
https://docs.aliyun.com/#/pub/dns/api-reference/record-related&UpdateDomainRecord

**Comment by tg123** [comment]
could you please run `goimports`, `vet` and `fmt` onto your codes.

I tested but not passed

**Comment by linuxlikerqq** [comment]
To:  denverdino:
    I fix it.
To: tg123:
    I runned go vet/fmt
    It relies only on github.com/denverdino/aliyungo, need to go get it first.
    For testing, need to change dns/config_test,  set APPID & KEY & Domain to your own.

**Comment by denverdino** [comment]
LGTM

Thanks again

**Comment by denverdino** [comment]
I just updated the README.md with DNS support and contributor list.

**Pull request merged**
