### PR TITLE
Get Bucket Info API support to oss

### PR DESCRIPTION
**Pull request by chainone**
1. Added support for Bucket Info
2. Removed config file, instead, use environment variables to unit test

### CODE REVIEW

**Comment by denverdino** [comment]
Thank you for your great contribution for Get Bucket Info.

For removing config file, my thought is to keep the config file for test or support the environment variables with default value.

**Comment by chainone** [comment]
I thought using env variables is better than hard-coded config file. What do you think?

**Comment by chainone** [comment]
But I do see some devs may prefer putting the key & secret in code to simply run the unit test.

I can do a change here to make the unit test respect the variables put in config file if no env variables is set.

**Comment by denverdino** [comment]
Thank you!

**Pull request merged**
