### PR TITLE
添加消息服务(MNS) ，支持队列单条消息的发送、消费和删除

### PR DESCRIPTION
**Pull request by hobo-c**

### CODE REVIEW

**Comment by denverdino** [comment]
Thanks for your contribution. Can you take a look for the following warnings? Thanks a lot
The command "eval go get -t -v ./... " failed. Retrying, 2 of 3.
github.com/denverdino/aliyungo/mns
# github.com/denverdino/aliyungo/mns
mns/queue.go:19: undefined: Queue
mns/queue.go:19: undefined: MsgSend
mns/queue.go:53: undefined: Queue
mns/queue.go:53: undefined: MsgReceive
mns/queue.go:73: undefined: MsgReceive
mns/queue.go:94: undefined: Queue

**Comment by denverdino** [comment]
The command "go get ./..." exited with 0.
0.59s$ go vet ./...
mns/client_test.go:63: arg resp for printf verb %s of wrong type: mns.MsgReceive
exit status 1

**Comment by denverdino** [comment]
Thanks for your contribution!

**Comment by hobo-c** [comment]
测试工作没做好，麻烦了^_^

**Comment by denverdino** [comment]
谢谢啦

**Pull request merged**
